version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - devops_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8084:80"
    networks:
      - devops_network
    depends_on:
      - mysql

  spring-app:
    build: .
    ports:
      - "8085:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/springdb?createDatabaseIfNotExist=true"
      spring.datasource.username: root
      spring.datasource.password: ""
      server.port: 8080
    networks:
      - devops_network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  devops_network:

volumes:
  mysql_data: